class Map:

  regions = [   'NAO',
                'MAO',
                'NWG',
                'IRI',
                'ENG',
                'HEL',
                'SKA',
                'BAL',
                'BOT',
                'BAR',
                'LYO',
                'WES',
                'TYS',
                'ADR',
                'ION',
                'AEG',
                'EAS',
                'BLA',
                'CLY',
                'EDI',
                'LVP',
                'YOR',
                'WAL',
                'LDN',
                'BRE',
                'PIC',
                'PAR',
                'BUR',
                'GAS',
                'MAR',
                'PIE',
                'POR',
                'SPA',
                'NAF',
                'TUN',
                'BEL',
                'HOL',
                'KIE',
                'RUH',
                'BER',
                'MUN',
                'PRU',
                'BOH',
                'SIL',
                'TYR',
                'VEN',
                'TUS',
                'ROM',
                'APU',
                'NAP',
                'DEN',
                'NWY',
                'SWE',
                'FIN',
                'VIE',
                'TRI',
                'WAR',
                'GAL',
                'BUD',
                'SER',
                'ALB',
                'GRE',
                'RUM',
                'BUL',
                'BUL_EC',
                'BUL_SC',
                'CON',
                'SMY',
                'ANK',
                'ARM',
                'SYR',
                'STP',
                'STP_NC',
                'STP_SC',
                'LVN',
                'MOS',
                'UKR',
                'SEV']
  
  multis = [['STP','STP_NC','STP_SC'],['BUL','BUL_EC','BUL_SC']]
  
  army_moves = [  ['CLY','EDI'],
                  ['CLY','LVP'],
                  ['EDI','YOR'],
                  ['EDI','LVP'],
                  ['YOR','WAL'],
                  ['WAL','LON'],
                  ['YOR','LON'],
                  ['YOR','LVP'],
                  ['LVP','WAL'],
                  ['POR','SPA'],
                  ['SPA','GAS'],
                  ['SPA','MAR'],
                  ['GAS','BRE'],
                  ['GAS','PAR'],
                  ['GAS','BUR'],
                  ['GAS','MAR'],
                  
                  
  
  def __init__(self):
    pass
    
